
[env]
WINIT_X11_IME_FIX = "true"

[window]
startup_mode = "Maximized"

[window.padding]
x = 10
y = 0

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"

[font]
size = 11.5

[font.normal]
family = "JetBrains Mono NL Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrains Mono NL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono NL Nerd Font"
style = "Medium Italic"

[font.bold_italic]
family = "JetBrains Mono NL Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[general]
import = [
  "~/.config/alacritty/gruvbox-material-dark.toml"
]
